### ISSUE TITLE
Contract for functions with no input and/or no output?

### ISSUE THREAD

**Issue by mcandre** [sefaira/rho-contracts.js#15]
Could there be null input and/or null output support in rho-contracts?

I tried typing:

    var main = c.fun().wrap(function() { console.log('Booh.'); }).returns(); main();

and:

    var main = c.fun(c.nothing).wrap(function() { console.log('Booh.'); }).returns(c.nothing); main();

But I always get a generic error message when I do this:

    node_modules/rho-contracts/contract.impl.js:932 throw new ContractLibraryError

I'm using rho-contracts v0.0.5, Node.js v0.10.36.

**Comment by gmarceau** [comment]
The first example should read:

    var main = c.fun().returns(c.any).wrap(function() { console.log('Booh.'); })

In other words, the `returns` methods is on the contract, not on the wrapped function, and takes one argument. Through in reality you probably want to omit the `return` clause in this case, since it is equivalent to `.return(c.any)`

    var main = c.fun().wrap(function() { console.log('Booh.'); })

The second example shoud read:

    var main = c.fun().returns(c.value(undefined)).wrap(function() { console.log('Booh.'); })

The way javascript works, functions without an explicit return value returns the value `undefined`, which is not equivalent to returning nothing. Only functions that always throw exceptions return nothing.

**Comment by mcandre** [comment]
Thank you for the detailed response.

Could rho-contracts offer a convenience syntax for `.returns(c.value(undefined))` to indicate *action* functions that should NOT return anything (other than the JS standard `undefined`?

**Comment by mcandre** [comment]
In case you're interested, I've updated most of my NPM packages to use rho-contracts, so feel free to grab examples from my source code.

https://www.npmjs.com/~mcandre

**Comment by gmarceau** [comment]
Neat!
